server:
    port: 9001
#mysqls
spring:
    datasource:
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/scrapy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8

#mybatis-plus
mybatis-plus:
    mapper-locations: classpath:com/pack/dao/mapping/*.xml
    type-aliases-package: com.pack.entity
    global-config:
        #逻辑删除
        db-config:
            logic-delete-value: 1 # 逻辑已删除值(默认为 1)
            logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    configuration:
        #可以通过设置map-underscore-to-camel-case属性为true来开启驼峰功能。
        map-underscore-to-camel-case: true
        auto-mapping-behavior: full
        cache-enabled: false  #配置的缓存的全局开关
        log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl



# 日志
#logging:
#    level:
#        com.pack.dao.mapper:
#            debug
